spring.application.name=demo


# =================| DATA BASE (H2) |=========================
spring.datasource.url=jdbc:h2:mem:ecommerce
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true


# ==============| JPA / HIBERNATE |===============
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true


# ================| GRAPHQL |===================

spring.graphql.graphiql.enabled=true